name: hello-udst 
 
on: push 
 
jobs: 
  hello-udst-job: 
    runs-on: ubuntu-latest 
     
    steps: 
      - name: Check out repository code 
        uses: actions/checkout@v3 
       
      - name: Print Hello UDST Message 
        run: echo "Hello UDST!" 
       
      - name: Print current date 
        run: date 
       
      - name: List repository files 
        run: ls -la 
